### ISSUE TITLE
Python format string coloring

### ISSUE THREAD

**Issue by Yevgnen** [meocoder31099/Serendipity-Theme-Zed#1]
The f-string in Python is not colored properly.

<img width="533" alt="image" src="https://github.com/meocoder31099/Serendipity-Theme-Zed/assets/16749790/aafb315c-69e3-404a-aa34-6ea35f36a60a">
<img width="579" alt="image" src="https://github.com/meocoder31099/Serendipity-Theme-Zed/assets/16749790/0b6fc0f8-5e5a-46d2-91a8-1938a82d8f94">

**Comment by meocoder31099** [comment]
@Yevgnen  Thank you for reporting the issue with the f-string not being colored properly. I have fixed the bug, and the f-string should now be displayed with the correct syntax highlighting. Please let me know if you encounter any further issues

**Comment by Yevgnen** [comment]
Hello, thanks for the quick response. I uninstall and re-install the theme but the issue is still there. Do I need to wait for a new release of the extension or some Zed extension auto update period?

**Comment by meocoder31099** [comment]
I will open a PR to update the latest version for the theme in Zed's extension repository. It may take about a day for the approval.

If you want to immediately apply the latest updates from this repo, you can clone and install it via **install Dev Extension**.

**Comment by Yevgnen** [comment]
Thanks for the hint!
